image: jakzal/phpqa:php8.2

before_script:
    - composer install

cache: 
    paths:
        - vendor/

stages:
    - SecurityChecker
    - CodingRecomandation
    - UnitTests

security-checker:
    stage: SecurityChecker
    script:
        - local-php-security-checker composer.lock
    allow_failure: false

phpcs:
    stage: CodingRecomandation
    script:
        - phpcs -v --standard=PSR2 --ignore=./src/Kernel.php ./src
    allow_failure: false

phpstan:
    stage: CodingRecomandation
    script:
        - phpstan analyse ./src
    allow_failure: false

twig-lint:
    stage: CodingRecomandation
    script:
        - twig-lint lint ./templates
    allow_failure: false

phpunit:
    stage: UnitTests
    script:
        - php bin/phpunit
    allow_failure: false
